const userPayload = {
  login: 'D4nielJ',
  id: 79114233,
  node_id: 'MDQ6VXNlcjc5MTE0MjMz',
  avatar_url: 'https://avatars.githubusercontent.com/u/79114233?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/D4nielJ',
  html_url: 'https://github.com/D4nielJ',
  followers_url: 'https://api.github.com/users/D4nielJ/followers',
  following_url: 'https://api.github.com/users/D4nielJ/following{/other_user}',
  gists_url: 'https://api.github.com/users/D4nielJ/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/D4nielJ/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/D4nielJ/subscriptions',
  organizations_url: 'https://api.github.com/users/D4nielJ/orgs',
  repos_url: 'https://api.github.com/users/D4nielJ/repos',
  events_url: 'https://api.github.com/users/D4nielJ/events{/privacy}',
  received_events_url: 'https://api.github.com/users/D4nielJ/received_events',
  type: 'User',
  site_admin: false,
  name: 'D4niel J',
  company: null,
  blog: 'd4nielj.github.io/developer-portfolio/',
  location: 'Medellín, Colombia',
  email: 'd4niel.djm@gmail.com',
  hireable: true,
  bio: 'Student @ Microverse | Full Stack Developer | JavaScript, React and Redux | Looking forward to getting familiar with Ruby on Rails. Open to new opportunities.',
  twitter_username: null,
  public_repos: 32,
  public_gists: 1,
  followers: 22,
  following: 28,
  created_at: '2021-02-15T20:38:00Z',
  updated_at: '2021-09-10T15:48:38Z',
  private_gists: 0,
  total_private_repos: 1,
  owned_private_repos: 1,
  disk_usage: 49535,
  collaborators: 0,
  two_factor_authentication: false,
  plan: {
    name: 'pro',
    space: 976562499,
    collaborators: 0,
    private_repos: 9999,
  },
};

export default userPayload;
